# Generated by Django 2.1.3 on 2018-11-28 06:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='herobanner_button',
            field=models.URLField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='herobanner_description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Bottom Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='herobanner_heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
